Fix YAML file

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -44,7 +44,11 @@ phases:
   build:
     commands:
       - echo "Deployments started on $(date)"
-      - if [ -z "$ENV_NAME" ]; then echo "ERROR: ENV_NAME is not set!"; exit 1; fi
+      - |
+        if [ -z "$ENV_NAME" ]; then
+          echo "ERROR: ENV_NAME is not set!"
+          exit 1
+        fi
       - echo "ENV_NAME is set to: $ENV_NAME"
       - echo "Deploying with the Serverless Framework..."
       - npx serverless deploy -v -s "$ENV_NAME" --debug || { echo "Deployment failed!"; exit 1; }
